server:
  port: 8181

spring:
  data:
    redis:
      port: 6379
      host: 127.0.0.1
  elasticsearch:
    uris: http://${elasticsearch.host}:${elasticsearch.port}
    username: ${elasticsearch.username}
    password: ${elasticsearch.password}

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 951d4cdb
    virtual-host: /

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tigshop_java_new?character_set_server=utf8mb4&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
    username: root2
    password: 1397667
    hikari:
      # 最大连接池大小
      maximum-pool-size: 20
      # 连接超时时间（毫秒）
      connection-timeout: 30000
      # 空闲连接超时时间（毫秒）
      idle-timeout: 600000
      # 最小空闲连接数
      minimum-idle: 3
      # 连接的最大生命周期（毫秒）
      max-lifetime: 1800000
      # 连接测试查询语句
      connection-test-query: SELECT 1
      pool-name: HikariCP
      driver-class-name: com.mysql.cj.jdbc.Driver

file:
  upload-dir: /opt/uploads/

# Elasticsearch配置
elasticsearch:
  host: 192.168.8.231
  port: 9200
  username:
  password:
  ssl-verify: false
  timeout: 30
  retries: 3
  product-index: tigshop_products

