spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: ""

# 滑块验证码
aj:
  captcha:
    # 缓存类型
    cache-type: redis
    # blockPuzzle 滑块 clickWord 文字点选  default默认两者都实例化
    type: blockPuzzle
    # 右下角显示字
    water-mark: tigshop
    # 校验滑动拼图允许误差偏移量(默认5像素)
    slip-offset: 5
    # aes加密坐标开启或者禁用(true|false)
    aes-status: true
    # 滑动干扰项(0/1/2)
    interference-options: 1

# springdoc-openapi项目配置
springdoc:
  # API文档, 默认路径:swagger-ui.html
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  # 配置需要生成接口文档的扫描包路径
  packages-to-scan: com.tigshop.api.controller
  group-configs:
    - group: '搜索'
      paths-to-match: '/api/search/**'
    - group: '商户'
      paths-to-match: '/api/merchant/**'
    - group: '文章'
      paths-to-match: '/api/article/**'
    - group: '分销'
      paths-to-match: '/api/salesman/**'
    - group: '商品'
      paths-to-match: '/api/product/**'
    - group: '订单'
      paths-to-match: '/api/order/**'
    - group: '商品分类'
      paths-to-match: '/api/category/**'
    - group: '首页'
      paths-to-match: '/api/home/**'
    - group: '购物车'
      paths-to-match: '/api/cart/**'
    - group: '会员中心'
      paths-to-match: '/api/user/**'
    - group: '公共方法'
      paths-to-match: '/api/common/**'
    - group: '店铺'
      paths-to-match: '/api/shop/**'
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    com.tigshop: warn
    org.springframework: warn
    org.apache.ibatis: debug

tigshop:
  name: TigShop
  version: JAVA-B2C-PRO
  version-num: v5.2.2
  is-merchant: 0
  is-b2b: 0
  is-pro: 1
  is-overseas: 0
  is-vendor: 0
  is-o2o: 0

icoTigCss: https://at.alicdn.com/t/c/font_4441878_2rp6xtukhnh.css
