server:
  port: 8181

spring:
  data:
    redis:
      port: 6379
      host: tigshop-redis

  rabbitmq:
    host: tigshop-rabbitmq
    port: 5672
    username: admin
    password: 951d4cdb
    virtual-host: /

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tigshop-mysql:3306/tigshop-java?character_set_server=utf8mb4&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      # 最大连接池大小
      maximum-pool-size: 20
      # 连接超时时间（毫秒）
      connection-timeout: 30000
      # 空闲连接超时时间（毫秒）
      idle-timeout: 600000
      # 最小空闲连接数
      minimum-idle: 3
      # 连接的最大生命周期（毫秒）
      max-lifetime: 1800000
      # 连接测试查询语句
      connection-test-query: SELECT 1
      pool-name: HikariCP
      driver-class-name: com.mysql.cj.jdbc.Driver

file:
  upload-dir: /opt/uploads/

# Elasticsearch配置
elasticsearch:
  host: tigshop-elasticsearch
  port: 9200
  username: elastic
  password: IqNVnkbJblDk7GSOJdZr
  ssl-verify: false
  timeout: 30
  retries: 3
  product-index: tigshop_products